# Generated by Django 3.1.7 on 2021-04-21 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='category_book',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.PROTECT, to='tes.category'),
            preserve_default=False,
        ),
    ]
