# Generated by Django 3.1.7 on 2021-04-21 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tes', '0004_auto_20210421_0832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category_book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tes.category'),
        ),
    ]
