# Generated by Django 3.1.7 on 2021-04-21 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tes', '0005_auto_20210421_0834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('available', 'available'), ('rental', 'rental'), ('sold', 'sold')], max_length=100),
        ),
    ]
