# Generated by Django 3.1.7 on 2021-04-23 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tes', '0006_auto_20210421_0915'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='total_rental',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
